name: Lint

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  swiftlint:
    name: SwiftLint
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/realm/swiftlint:latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5

      - name: Run SwiftLint
        run: swiftlint lint --strict --reporter github-actions-logging
